TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.05
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 1
  acc_lim_y: 1

  # Differential drive
  holonomic_robot: false